INSERT INTO users (`username`, `password`, `starting_weight`, `target_weight`) VALUES ('Lance', '123', 190, 175);
INSERT INTO users (`username`, `password`, `starting_weight`, `target_weight`) VALUES ('Russell', '321', 180, 170);
INSERT INTO users (`username`, `password`, `starting_weight`, `target_weight`) VALUES ('Igor', '456', 190, 175);
INSERT INTO users (`username`, `password`, `starting_weight`, `target_weight`) VALUES ('Keith', '654', 180, 165);


INSERT INTO userweight (user_id, user_weight) VALUES (1, 195);
INSERT INTO userweight (user_id, user_weight) VALUES (1, 194);
INSERT INTO userweight (user_id, user_weight) VALUES (1, 193);
INSERT INTO userweight (user_id, user_weight) VALUES (1, 192);
INSERT INTO userweight (user_id, user_weight) VALUES (1, 191);
INSERT INTO userweight (user_id, user_weight) VALUES (2, 180);
INSERT INTO userweight (user_id, user_weight) VALUES (2, 179);
INSERT INTO userweight (user_id, user_weight) VALUES (2, 178);
INSERT INTO userweight (user_id, user_weight) VALUES (2, 176);
INSERT INTO userweight (user_id, user_weight) VALUES (2, 175);
INSERT INTO userweight (user_id, user_weight) VALUES (3, 190);
INSERT INTO userweight (user_id, user_weight) VALUES (3, 189);
INSERT INTO userweight (user_id, user_weight) VALUES (3, 188);
INSERT INTO userweight (user_id, user_weight) VALUES (3, 187);
INSERT INTO userweight (user_id, user_weight) VALUES (3, 176);
INSERT INTO userweight (user_id, user_weight) VALUES (4, 190);
INSERT INTO userweight (user_id, user_weight) VALUES (4, 189);
INSERT INTO userweight (user_id, user_weight) VALUES (4, 188);
INSERT INTO userweight (user_id, user_weight) VALUES (4, 187);
INSERT INTO userweight (user_id, user_weight) VALUES (4, 186);

INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (1, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (1, 'swim', 60, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (1, 'bike', 120, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (1, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (1, 'swim', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (2, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (2, 'swim', 60, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (2, 'bike', 120, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (2, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (2, 'swim', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (3, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (3, 'swim', 60, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (3, 'bike', 120, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (3, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (3, 'swim', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (4, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (4, 'swim', 60, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (4, 'bike', 120, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (4, 'run', 30, '2019-05-02', 400);
INSERT INTO activities (user_id, activity_name, activity_quantity, activity_date, total_cal_burn) VALUES (4, 'swim', 30, '2019-05-02', 400);

INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (1, 'ice cream', '2019-05-02', 400);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (1, 'hot dog', '2019-05-01', 200);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (1, 'cake', '2019-05-01', 300);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (1, 'cereal', '2019-05-01', 350);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (1, 'chips', '2019-05-01', '125');
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (2, 'ice cream', '2019-05-02', 400);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (2, 'hot dog', '2019-05-01', 200);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (2, 'cake', '2019-05-01', 300);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (2, 'cereal', '2019-05-01', 350);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (2, 'chips', '2019-05-01', '125');
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (3, 'ice cream', '2019-05-02', 400);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (3, 'hot dog', '2019-05-01', 200);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (3, 'cake', '2019-05-01', 300);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (3, 'cereal', '2019-05-01', 350);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (3, 'chips', '2019-05-01', '125');
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (4, 'ice cream', '2019-05-02', 400);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (4, 'hot dog', '2019-05-01', 200);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (4, 'cake', '2019-05-01', 300);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (4, 'cereal', '2019-05-01', 350);
INSERT INTO calories (user_id, `food_name`, `food_date`, `total_cal_con`) VALUES (4, 'chips', '2019-05-01', '125');
